package com.mygym.model;
import com.netu.lib.ApplicationService;
import com.netu.lib.DBUtils;
import com.netu.lib.Model.ModelObject;
import com.netu.lib.db.ConnectionPool;

import java.sql.Connection;
import org.json.JSONObject;

import com.mygym.model.workout.WorkoutExercise;
import com.mygym.model.workout.WorkoutExerciseDBMapper;
import com.mygym.model.ExerciseDefinition;
import com.mygym.model.ExerciseDefinitionDBMapper;
import com.mygym.model.BodyPart;
import com.mygym.model.BodyPartDBMapper;
import com.mygym.model.Equipment;
import com.mygym.model.EquipmentDBMapper;
import com.mygym.model.workout.ExecutedWorkout;
import com.mygym.model.workout.ExecutedWorkoutDBMapper;
import com.mygym.model.workout.WorkoutDefinition;
import com.mygym.model.workout.WorkoutDefinitionDBMapper;
import com.mygym.model.security.SystemUser;
import com.mygym.model.security.SystemUserDBMapper;
import com.mygym.model.ExerciseTypeLink;
import com.mygym.model.ExerciseTypeLinkDBMapper;
import com.mygym.model.BodyPartExercise;
import com.mygym.model.BodyPartExerciseDBMapper;
import com.mygym.model.ExerciseType;
import com.mygym.model.ExerciseTypeDBMapper;


import javax.annotation.Generated;
import org.junit.AfterClass;
import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;

import com.netu.lib.TestUtils;

@Generated(
        value = {"com.netu.codeGen.XMLModelGenerator, Version 3"},
        comments = "junit tests ",
        date = "Wed Jan 20 15:35:51 EET 2021"
    ) 
/**
 * Class autogenerated on <DATE>Wed Jan 20 15:35:51 EET 2021</DATE> by com.netu.codeGen.XMLModelGenerator.
 * This class is used to test all modelobjects for project 
 * <b>DO NOT change code in this class.</b> 
 */
public class TestMyGymModel {
	
	java.util.Properties testProps = com.netu.lib.NetuUtils.getProperties("nuftests.properties");

    //Use TestInitialize to run code before running each test
    @BeforeClass
    public static void setUp()  throws Exception  {
		TestUtils.configureNUFTestsForOracle();
		Connection c = ConnectionPool.getConn();
        ApplicationService.newCurrent(c, "test");
		
    }
	
    @AfterClass
    public static void tearDown() {
		ApplicationService.release();
    }

    @Test
	public void testWorkoutExercise() throws Exception  {
        
		ApplicationService.beginTrans();
		System.err.println("testing WorkoutExercise"  );
		try {
			
			final WorkoutExerciseDBMapper pdb = new WorkoutExerciseDBMapper();
			final String newvals = (String) testProps.get("WorkoutExerciseNew");
			
			if (newvals !=null ) {
				// to test put this in nuafTests.properties
				// WorkoutExerciseNew={"WorkoutId":"","Sequence":"","ExerciseId":"","NumberOfSets":"","RepetitionsEachSet":"","DurationSeconds":"","RestSeconds":"", }
				JSONObject jsn = new JSONObject(newvals);
				WorkoutExercise newmo = new WorkoutExercise();
					
			newmo.setWorkoutId(jsn.optString("WorkoutId",null));
			newmo.setSequence(jsn.optString("Sequence",null));
			newmo.setExerciseId(jsn.optString("ExerciseId",null));
			newmo.setNumberOfSets(jsn.optString("NumberOfSets",null));
			newmo.setRepetitionsEachSet(jsn.optString("RepetitionsEachSet",null));
			newmo.setDurationSeconds(jsn.optString("DurationSeconds",null));
			newmo.setRestSeconds(jsn.optString("RestSeconds",null));

				pdb.save(newmo);  // save new record
				newmo.setDirty(true); // make dirty so we test update
				pdb.save(newmo);  // this will do update

				final Object newmoId = newmo.getId();
				Assert.assertNotNull(newmoId);
				pdb.delete( newmo ); // this will do delete

				Assert.assertNull(pdb.find(newmoId));	
				
			} else {	

				final Object pid = DBUtils.getValue("select workout_exercise_id from workout_exercise  limit 1,1");
				if(pid!=null) {	

					WorkoutExercise p = (WorkoutExercise)pdb.findOne("workout_exercise_id=?",pid);
					final WorkoutExercise p2 =  (WorkoutExercise)p.clone();			
			
			Assert.assertEquals("Expected Field workout_id to be equal",p.getWorkoutId(), p2.getWorkoutId());
			Assert.assertEquals("Expected Field sequence to be equal",p.getSequence(), p2.getSequence());
			Assert.assertEquals("Expected Field exercise_id to be equal",p.getExerciseId(), p2.getExerciseId());
			Assert.assertEquals("Expected Field number_of_sets to be equal",p.getNumberOfSets(), p2.getNumberOfSets());
			Assert.assertEquals("Expected Field repetitions_each_set to be equal",p.getRepetitionsEachSet(), p2.getRepetitionsEachSet());
			Assert.assertEquals("Expected Field duration_seconds to be equal",p.getDurationSeconds(), p2.getDurationSeconds());
			Assert.assertEquals("Expected Field rest_seconds to be equal",p.getRestSeconds(), p2.getRestSeconds());
			Assert.assertEquals("Expected Field create_date to be equal",p.getCreateDate(), p2.getCreateDate());
			//-- no check for fields update date and update user
			Assert.assertEquals("Expected Field create_user to be equal",p.getCreateUser(), p2.getCreateUser());
			//-- no check for fields update date and update user

					p.setDirty(true); //force save
					pdb.save(p);

					//now reload object from database
					p = (WorkoutExercise)pdb.findOne("workout_exercise_id=?",pid);
					Assert.assertNotNull( p );
				} else { 
					System.err.println("  --Warning: No records found of type WorkoutExercise"  );
				}

			}

		} finally {
			ApplicationService.rollbackTrans();
			// note: do not release here! It happens in tear down
		}
            
        
    }

    @Test
	public void testExerciseDefinition() throws Exception  {
        
		ApplicationService.beginTrans();
		System.err.println("testing ExerciseDefinition"  );
		try {
			
			final ExerciseDefinitionDBMapper pdb = new ExerciseDefinitionDBMapper();
			final String newvals = (String) testProps.get("ExerciseDefinitionNew");
			
			if (newvals !=null ) {
				// to test put this in nuafTests.properties
				// ExerciseDefinitionNew={"Name":"","VideoUrl":"","Description":"","EquipmentId":"", }
				JSONObject jsn = new JSONObject(newvals);
				ExerciseDefinition newmo = new ExerciseDefinition();
					
			newmo.setName(jsn.optString("Name",null));
			newmo.setVideoUrl(jsn.optString("VideoUrl",null));
			newmo.setDescription(jsn.optString("Description",null));
			newmo.setEquipmentId(jsn.optString("EquipmentId",null));

				pdb.save(newmo);  // save new record
				newmo.setDirty(true); // make dirty so we test update
				pdb.save(newmo);  // this will do update

				final Object newmoId = newmo.getId();
				Assert.assertNotNull(newmoId);
				pdb.delete( newmo ); // this will do delete

				Assert.assertNull(pdb.find(newmoId));	
				
			} else {	

				final Object pid = DBUtils.getValue("select exercise_definition_id from exercise_definition  limit 1,1");
				if(pid!=null) {	

					ExerciseDefinition p = (ExerciseDefinition)pdb.findOne("exercise_definition_id=?",pid);
					final ExerciseDefinition p2 =  (ExerciseDefinition)p.clone();			
			
			Assert.assertEquals("Expected Field name to be equal",p.getName(), p2.getName());
			Assert.assertEquals("Expected Field video_url to be equal",p.getVideoUrl(), p2.getVideoUrl());
			Assert.assertEquals("Expected Field description to be equal",p.getDescription(), p2.getDescription());
			Assert.assertEquals("Expected Field equipment_id to be equal",p.getEquipmentId(), p2.getEquipmentId());
			Assert.assertEquals("Expected Field create_date to be equal",p.getCreateDate(), p2.getCreateDate());
			//-- no check for fields update date and update user
			Assert.assertEquals("Expected Field create_user to be equal",p.getCreateUser(), p2.getCreateUser());
			//-- no check for fields update date and update user
//*** below we are testing loading of associated objects:
			p.getBodyPartsAffected();
			p.getExerciseTypes();
			p.getEquipmentNeeded();

					p.setDirty(true); //force save
					pdb.save(p);

					//now reload object from database
					p = (ExerciseDefinition)pdb.findOne("exercise_definition_id=?",pid);
					Assert.assertNotNull( p );
				} else { 
					System.err.println("  --Warning: No records found of type ExerciseDefinition"  );
				}

			}

		} finally {
			ApplicationService.rollbackTrans();
			// note: do not release here! It happens in tear down
		}
            
        
    }

    @Test
	public void testBodyPart() throws Exception  {
        
		ApplicationService.beginTrans();
		System.err.println("testing BodyPart"  );
		try {
			
			final BodyPartDBMapper pdb = new BodyPartDBMapper();
			final String newvals = (String) testProps.get("BodyPartNew");
			
			if (newvals !=null ) {
				// to test put this in nuafTests.properties
				// BodyPartNew={"BodyPartName":"", }
				JSONObject jsn = new JSONObject(newvals);
				BodyPart newmo = new BodyPart();
					
			newmo.setBodyPartName(jsn.optString("BodyPartName",null));

				pdb.save(newmo);  // save new record
				newmo.setDirty(true); // make dirty so we test update
				pdb.save(newmo);  // this will do update

				final Object newmoId = newmo.getId();
				Assert.assertNotNull(newmoId);
				pdb.delete( newmo ); // this will do delete

				Assert.assertNull(pdb.find(newmoId));	
				
			} else {	

				final Object pid = DBUtils.getValue("select body_part_id from body_part  limit 1,1");
				if(pid!=null) {	

					BodyPart p = (BodyPart)pdb.findOne("body_part_id=?",pid);
					final BodyPart p2 =  (BodyPart)p.clone();			
			
			Assert.assertEquals("Expected Field body_part_name to be equal",p.getBodyPartName(), p2.getBodyPartName());
			Assert.assertEquals("Expected Field create_date to be equal",p.getCreateDate(), p2.getCreateDate());
			//-- no check for fields update date and update user
			Assert.assertEquals("Expected Field create_user to be equal",p.getCreateUser(), p2.getCreateUser());
			//-- no check for fields update date and update user
//*** below we are testing loading of associated objects:
			p.getBodyPart();

					p.setDirty(true); //force save
					pdb.save(p);

					//now reload object from database
					p = (BodyPart)pdb.findOne("body_part_id=?",pid);
					Assert.assertNotNull( p );
				} else { 
					System.err.println("  --Warning: No records found of type BodyPart"  );
				}

			}

		} finally {
			ApplicationService.rollbackTrans();
			// note: do not release here! It happens in tear down
		}
            
        
    }

    @Test
	public void testEquipment() throws Exception  {
        
		ApplicationService.beginTrans();
		System.err.println("testing Equipment"  );
		try {
			
			final EquipmentDBMapper pdb = new EquipmentDBMapper();
			final String newvals = (String) testProps.get("EquipmentNew");
			
			if (newvals !=null ) {
				// to test put this in nuafTests.properties
				// EquipmentNew={"EquipmentName":"", }
				JSONObject jsn = new JSONObject(newvals);
				Equipment newmo = new Equipment();
					
			newmo.setEquipmentName(jsn.optString("EquipmentName",null));

				pdb.save(newmo);  // save new record
				newmo.setDirty(true); // make dirty so we test update
				pdb.save(newmo);  // this will do update

				final Object newmoId = newmo.getId();
				Assert.assertNotNull(newmoId);
				pdb.delete( newmo ); // this will do delete

				Assert.assertNull(pdb.find(newmoId));	
				
			} else {	

				final Object pid = DBUtils.getValue("select equipment_id from equipment  limit 1,1");
				if(pid!=null) {	

					Equipment p = (Equipment)pdb.findOne("equipment_id=?",pid);
					final Equipment p2 =  (Equipment)p.clone();			
			
			Assert.assertEquals("Expected Field equipment_name to be equal",p.getEquipmentName(), p2.getEquipmentName());
			Assert.assertEquals("Expected Field create_date to be equal",p.getCreateDate(), p2.getCreateDate());
			//-- no check for fields update date and update user
			Assert.assertEquals("Expected Field create_user to be equal",p.getCreateUser(), p2.getCreateUser());
			//-- no check for fields update date and update user

					p.setDirty(true); //force save
					pdb.save(p);

					//now reload object from database
					p = (Equipment)pdb.findOne("equipment_id=?",pid);
					Assert.assertNotNull( p );
				} else { 
					System.err.println("  --Warning: No records found of type Equipment"  );
				}

			}

		} finally {
			ApplicationService.rollbackTrans();
			// note: do not release here! It happens in tear down
		}
            
        
    }

    @Test
	public void testExecutedWorkout() throws Exception  {
        
		ApplicationService.beginTrans();
		System.err.println("testing ExecutedWorkout"  );
		try {
			
			final ExecutedWorkoutDBMapper pdb = new ExecutedWorkoutDBMapper();
			final String newvals = (String) testProps.get("ExecutedWorkoutNew");
			
			if (newvals !=null ) {
				// to test put this in nuafTests.properties
				// ExecutedWorkoutNew={"SystemUserId":"","WorkoutStart":"","WorkoutEnd":"","Notes":"","ScheduledWorkoutId":"","WorkoutDefinitionId":"", }
				JSONObject jsn = new JSONObject(newvals);
				ExecutedWorkout newmo = new ExecutedWorkout();
					
			newmo.setSystemUserId(jsn.optString("SystemUserId",null));
			newmo.setWorkoutStart(jsn.optString("WorkoutStart",null));
			newmo.setWorkoutEnd(jsn.optString("WorkoutEnd",null));
			newmo.setNotes(jsn.optString("Notes",null));
			newmo.setScheduledWorkoutId(jsn.optString("ScheduledWorkoutId",null));
			newmo.setWorkoutDefinitionId(jsn.optString("WorkoutDefinitionId",null));

				pdb.save(newmo);  // save new record
				newmo.setDirty(true); // make dirty so we test update
				pdb.save(newmo);  // this will do update

				final Object newmoId = newmo.getId();
				Assert.assertNotNull(newmoId);
				pdb.delete( newmo ); // this will do delete

				Assert.assertNull(pdb.find(newmoId));	
				
			} else {	

				final Object pid = DBUtils.getValue("select workout_id from workout  limit 1,1");
				if(pid!=null) {	

					ExecutedWorkout p = (ExecutedWorkout)pdb.findOne("workout_id=?",pid);
					final ExecutedWorkout p2 =  (ExecutedWorkout)p.clone();			
			
			Assert.assertEquals("Expected Field system_user_id to be equal",p.getSystemUserId(), p2.getSystemUserId());
			Assert.assertEquals("Expected Field workout_start to be equal",p.getWorkoutStart(), p2.getWorkoutStart());
			Assert.assertEquals("Expected Field workout_end to be equal",p.getWorkoutEnd(), p2.getWorkoutEnd());
			Assert.assertEquals("Expected Field notes to be equal",p.getNotes(), p2.getNotes());
			Assert.assertEquals("Expected Field scheduled_workout_id to be equal",p.getScheduledWorkoutId(), p2.getScheduledWorkoutId());
			Assert.assertEquals("Expected Field workout_definition_id to be equal",p.getWorkoutDefinitionId(), p2.getWorkoutDefinitionId());
			Assert.assertEquals("Expected Field create_date to be equal",p.getCreateDate(), p2.getCreateDate());
			//-- no check for fields update date and update user
			Assert.assertEquals("Expected Field create_user to be equal",p.getCreateUser(), p2.getCreateUser());
			//-- no check for fields update date and update user

					p.setDirty(true); //force save
					pdb.save(p);

					//now reload object from database
					p = (ExecutedWorkout)pdb.findOne("workout_id=?",pid);
					Assert.assertNotNull( p );
				} else { 
					System.err.println("  --Warning: No records found of type ExecutedWorkout"  );
				}

			}

		} finally {
			ApplicationService.rollbackTrans();
			// note: do not release here! It happens in tear down
		}
            
        
    }

    @Test
	public void testWorkoutDefinition() throws Exception  {
        
		ApplicationService.beginTrans();
		System.err.println("testing WorkoutDefinition"  );
		try {
			
			final WorkoutDefinitionDBMapper pdb = new WorkoutDefinitionDBMapper();
			final String newvals = (String) testProps.get("WorkoutDefinitionNew");
			
			if (newvals !=null ) {
				// to test put this in nuafTests.properties
				// WorkoutDefinitionNew={"Name":"","Description":"", }
				JSONObject jsn = new JSONObject(newvals);
				WorkoutDefinition newmo = new WorkoutDefinition();
					
			newmo.setName(jsn.optString("Name",null));
			newmo.setDescription(jsn.optString("Description",null));

				pdb.save(newmo);  // save new record
				newmo.setDirty(true); // make dirty so we test update
				pdb.save(newmo);  // this will do update

				final Object newmoId = newmo.getId();
				Assert.assertNotNull(newmoId);
				pdb.delete( newmo ); // this will do delete

				Assert.assertNull(pdb.find(newmoId));	
				
			} else {	

				final Object pid = DBUtils.getValue("select WORKOUT_DEFINITION_ID from workout_definition  limit 1,1");
				if(pid!=null) {	

					WorkoutDefinition p = (WorkoutDefinition)pdb.findOne("WORKOUT_DEFINITION_ID=?",pid);
					final WorkoutDefinition p2 =  (WorkoutDefinition)p.clone();			
			
			Assert.assertEquals("Expected Field name to be equal",p.getName(), p2.getName());
			Assert.assertEquals("Expected Field description to be equal",p.getDescription(), p2.getDescription());
			Assert.assertEquals("Expected Field create_date to be equal",p.getCreateDate(), p2.getCreateDate());
			//-- no check for fields update date and update user
			Assert.assertEquals("Expected Field create_user to be equal",p.getCreateUser(), p2.getCreateUser());
			//-- no check for fields update date and update user

					p.setDirty(true); //force save
					pdb.save(p);

					//now reload object from database
					p = (WorkoutDefinition)pdb.findOne("WORKOUT_DEFINITION_ID=?",pid);
					Assert.assertNotNull( p );
				} else { 
					System.err.println("  --Warning: No records found of type WorkoutDefinition"  );
				}

			}

		} finally {
			ApplicationService.rollbackTrans();
			// note: do not release here! It happens in tear down
		}
            
        
    }

    @Test
	public void testSystemUser() throws Exception  {
        
		ApplicationService.beginTrans();
		System.err.println("testing SystemUser"  );
		try {
			
			final SystemUserDBMapper pdb = new SystemUserDBMapper();
			final String newvals = (String) testProps.get("SystemUserNew");
			
			if (newvals !=null ) {
				// to test put this in nuafTests.properties
				// SystemUserNew={"Email":"","Password":"","IsActive":"", }
				JSONObject jsn = new JSONObject(newvals);
				SystemUser newmo = new SystemUser();
					
			newmo.setEmail(jsn.optString("Email",null));
			newmo.setPassword(jsn.optString("Password",null));
			newmo.setIsActive(jsn.optString("IsActive",null));

				pdb.save(newmo);  // save new record
				newmo.setDirty(true); // make dirty so we test update
				pdb.save(newmo);  // this will do update

				final Object newmoId = newmo.getId();
				Assert.assertNotNull(newmoId);
				pdb.delete( newmo ); // this will do delete

				Assert.assertNull(pdb.find(newmoId));	
				
			} else {	

				final Object pid = DBUtils.getValue("select system_user_id from system_user  limit 1,1");
				if(pid!=null) {	

					SystemUser p = (SystemUser)pdb.findOne("system_user_id=?",pid);
					final SystemUser p2 =  (SystemUser)p.clone();			
			
			Assert.assertEquals("Expected Field email to be equal",p.getEmail(), p2.getEmail());
			Assert.assertEquals("Expected Field password to be equal",p.getPassword(), p2.getPassword());
			Assert.assertEquals("Expected Field is_active to be equal",p.getIsActive(), p2.getIsActive());
			Assert.assertEquals("Expected Field create_date to be equal",p.getCreateDate(), p2.getCreateDate());
			//-- no check for fields update date and update user
			Assert.assertEquals("Expected Field create_user to be equal",p.getCreateUser(), p2.getCreateUser());
			//-- no check for fields update date and update user

					p.setDirty(true); //force save
					pdb.save(p);

					//now reload object from database
					p = (SystemUser)pdb.findOne("system_user_id=?",pid);
					Assert.assertNotNull( p );
				} else { 
					System.err.println("  --Warning: No records found of type SystemUser"  );
				}

			}

		} finally {
			ApplicationService.rollbackTrans();
			// note: do not release here! It happens in tear down
		}
            
        
    }

    @Test
	public void testExerciseTypeLink() throws Exception  {
        
		ApplicationService.beginTrans();
		System.err.println("testing ExerciseTypeLink"  );
		try {
			
			final ExerciseTypeLinkDBMapper pdb = new ExerciseTypeLinkDBMapper();
			final String newvals = (String) testProps.get("ExerciseTypeLinkNew");
			
			if (newvals !=null ) {
				// to test put this in nuafTests.properties
				// ExerciseTypeLinkNew={"ExerciseTypeId":"","ExerciseId":"", }
				JSONObject jsn = new JSONObject(newvals);
				ExerciseTypeLink newmo = new ExerciseTypeLink();
					
			newmo.setExerciseTypeId(jsn.optString("ExerciseTypeId",null));
			newmo.setExerciseId(jsn.optString("ExerciseId",null));

				pdb.save(newmo);  // save new record
				newmo.setDirty(true); // make dirty so we test update
				pdb.save(newmo);  // this will do update

				final Object newmoId = newmo.getId();
				Assert.assertNotNull(newmoId);
				pdb.delete( newmo ); // this will do delete

				Assert.assertNull(pdb.find(newmoId));	
				
			} else {	

				final Object pid = DBUtils.getValue("select exercise_type_link_id from exercise_type_link  limit 1,1");
				if(pid!=null) {	

					ExerciseTypeLink p = (ExerciseTypeLink)pdb.findOne("exercise_type_link_id=?",pid);
					final ExerciseTypeLink p2 =  (ExerciseTypeLink)p.clone();			
			
			Assert.assertEquals("Expected Field exercise_type_id to be equal",p.getExerciseTypeId(), p2.getExerciseTypeId());
			Assert.assertEquals("Expected Field exercise_id to be equal",p.getExerciseId(), p2.getExerciseId());
			Assert.assertEquals("Expected Field create_date to be equal",p.getCreateDate(), p2.getCreateDate());
			//-- no check for fields update date and update user
			Assert.assertEquals("Expected Field create_user to be equal",p.getCreateUser(), p2.getCreateUser());
			//-- no check for fields update date and update user
//*** below we are testing loading of associated objects:
			p.getExerciseType();

					p.setDirty(true); //force save
					pdb.save(p);

					//now reload object from database
					p = (ExerciseTypeLink)pdb.findOne("exercise_type_link_id=?",pid);
					Assert.assertNotNull( p );
				} else { 
					System.err.println("  --Warning: No records found of type ExerciseTypeLink"  );
				}

			}

		} finally {
			ApplicationService.rollbackTrans();
			// note: do not release here! It happens in tear down
		}
            
        
    }

    @Test
	public void testBodyPartExercise() throws Exception  {
        
		ApplicationService.beginTrans();
		System.err.println("testing BodyPartExercise"  );
		try {
			
			final BodyPartExerciseDBMapper pdb = new BodyPartExerciseDBMapper();
			final String newvals = (String) testProps.get("BodyPartExerciseNew");
			
			if (newvals !=null ) {
				// to test put this in nuafTests.properties
				// BodyPartExerciseNew={"BodyPartId":"","ExerciseId":"", }
				JSONObject jsn = new JSONObject(newvals);
				BodyPartExercise newmo = new BodyPartExercise();
					
			newmo.setBodyPartId(jsn.optString("BodyPartId",null));
			newmo.setExerciseId(jsn.optString("ExerciseId",null));

				pdb.save(newmo);  // save new record
				newmo.setDirty(true); // make dirty so we test update
				pdb.save(newmo);  // this will do update

				final Object newmoId = newmo.getId();
				Assert.assertNotNull(newmoId);
				pdb.delete( newmo ); // this will do delete

				Assert.assertNull(pdb.find(newmoId));	
				
			} else {	

				final Object pid = DBUtils.getValue("select body_part_exercise_id from body_part_exercise  limit 1,1");
				if(pid!=null) {	

					BodyPartExercise p = (BodyPartExercise)pdb.findOne("body_part_exercise_id=?",pid);
					final BodyPartExercise p2 =  (BodyPartExercise)p.clone();			
			
			Assert.assertEquals("Expected Field body_part_id to be equal",p.getBodyPartId(), p2.getBodyPartId());
			Assert.assertEquals("Expected Field exercise_id to be equal",p.getExerciseId(), p2.getExerciseId());
			Assert.assertEquals("Expected Field create_date to be equal",p.getCreateDate(), p2.getCreateDate());
			//-- no check for fields update date and update user
			Assert.assertEquals("Expected Field create_user to be equal",p.getCreateUser(), p2.getCreateUser());
			//-- no check for fields update date and update user
//*** below we are testing loading of associated objects:
			p.getBodyPart();

					p.setDirty(true); //force save
					pdb.save(p);

					//now reload object from database
					p = (BodyPartExercise)pdb.findOne("body_part_exercise_id=?",pid);
					Assert.assertNotNull( p );
				} else { 
					System.err.println("  --Warning: No records found of type BodyPartExercise"  );
				}

			}

		} finally {
			ApplicationService.rollbackTrans();
			// note: do not release here! It happens in tear down
		}
            
        
    }

    @Test
	public void testExerciseType() throws Exception  {
        
		ApplicationService.beginTrans();
		System.err.println("testing ExerciseType"  );
		try {
			
			final ExerciseTypeDBMapper pdb = new ExerciseTypeDBMapper();
			final String newvals = (String) testProps.get("ExerciseTypeNew");
			
			if (newvals !=null ) {
				// to test put this in nuafTests.properties
				// ExerciseTypeNew={"ExerciseType":"", }
				JSONObject jsn = new JSONObject(newvals);
				ExerciseType newmo = new ExerciseType();
					
			newmo.setExerciseType(jsn.optString("ExerciseType",null));

				pdb.save(newmo);  // save new record
				newmo.setDirty(true); // make dirty so we test update
				pdb.save(newmo);  // this will do update

				final Object newmoId = newmo.getId();
				Assert.assertNotNull(newmoId);
				pdb.delete( newmo ); // this will do delete

				Assert.assertNull(pdb.find(newmoId));	
				
			} else {	

				final Object pid = DBUtils.getValue("select exercise_type_id from exercise_type  limit 1,1");
				if(pid!=null) {	

					ExerciseType p = (ExerciseType)pdb.findOne("exercise_type_id=?",pid);
					final ExerciseType p2 =  (ExerciseType)p.clone();			
			
			Assert.assertEquals("Expected Field exercise_type to be equal",p.getExerciseType(), p2.getExerciseType());
			Assert.assertEquals("Expected Field create_date to be equal",p.getCreateDate(), p2.getCreateDate());
			//-- no check for fields update date and update user
			Assert.assertEquals("Expected Field create_user to be equal",p.getCreateUser(), p2.getCreateUser());
			//-- no check for fields update date and update user

					p.setDirty(true); //force save
					pdb.save(p);

					//now reload object from database
					p = (ExerciseType)pdb.findOne("exercise_type_id=?",pid);
					Assert.assertNotNull( p );
				} else { 
					System.err.println("  --Warning: No records found of type ExerciseType"  );
				}

			}

		} finally {
			ApplicationService.rollbackTrans();
			// note: do not release here! It happens in tear down
		}
            
        
    }



}