package com.mygym.model;

/**
 * Class autogenerated on <DATE>Tue Oct 20 21:24:13 EEST 2020</DATE> by com.netu.codeGen.XMLModelGenerator
 * Feel Free to change the generated code. 
 */
public class BodyPartExercise extends BodyPartExerciseModelBase  {

  
}
