package com.mygym.model;

import com.netu.lib.ApplicationService;
import com.netu.lib.DBUtils;
import com.netu.lib.Model.MODeleteViolationException;
import com.netu.lib.Model.MOTranslatedValidationException;
import com.netu.lib.Model.ModelObject;

import com.netu.lib.db.ConnectionPool;

import com.netu.lib.db.DBMapper;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Types;
import com.netu.lib.Model.ModelObjectList;
import com.netu.lib.db.MySQLDBMapper;
import com.netu.lib.Model.annotations.DMLQueries;

import javax.annotation.Generated;

/**
 * Gen: Version 3, MapperBase.mysql.txt
 * Class autogenerated on <DATE>Wed Jan 20 12:07:47 EET 2021</DATE> by com.netu.codeGen.XMLModelGenerator.<br>
 * Class for Database Data Mapper Pattern for table <b>body_part</b>.<br>
 * <b>!!!!!!!! DO NOT MODIFY CODE OF THIS CLASS!!!!!!!!</b><br>
 * This class has the responsibility of loading 
 * data into Model Objects, and saving them back to 
 * the Database
 */
@Generated(
        value = {"com.netu.codeGen.XMLModelGenerator"},
        comments = "Mapper Object for table body_part ",
        date = "Wed Jan 20 12:07:47 EET 2021"
    )
@DMLQueries(
	update="update body_part set body_part_name=?,create_date=?,update_date=?,create_user=?,update_user=? where body_part_id=?",
	updateRowid="",
	delete="DELETE FROM body_part WHERE body_part_id=?",
	deleteRowid="",
	insert="insert into body_part (body_part_name,create_date,update_date,create_user,update_user) values (?,?,?,?,?)",
	selectone="SELECT t.body_part_id, t.body_part_name, t.create_date, t.update_date, t.create_user, t.update_user FROM  body_part t  WHERE body_part_id=?",
	selectall="SELECT t.body_part_id, t.body_part_name, t.create_date, t.update_date, t.create_user, t.update_user FROM  body_part t ",
	pagingSelect="SELECT t.body_part_id, t.body_part_name, t.create_date, t.update_date, t.create_user, t.update_user FROM  body_part t  {criteria} LIMIT {offset}, {pageSize}")
public class BodyPartDBMapper extends MySQLDBMapper  {
	
	public BodyPartDBMapper(Connection c) {
		super(c);
	}
	public BodyPartDBMapper() {
                // empty constructor, used in dynamic instantiations
		// will get a connection from the ApplicationService
		super();
	}
	
	/**
	* Clients can override this to return a custom class for loading
	*/
	public BodyPart getInstanceForLoad() {
		
		return new BodyPart();
		
	}
		
	public ModelObject load(Object ors) {
		
		ResultSet rs = (ResultSet)ors;
		
		BodyPart ret = this.getInstanceForLoad();
		try {
			ret.setLoading(true);
			
			ret.setBodyPartId(readInt(rs,BodyPart.FLD_BODY_PART_ID));
			ret.setBodyPartName(rs.getString(BodyPart.FLD_BODY_PART_NAME));
			ret.setCreateDate(readTimeStamp(rs,BodyPart.FLD_CREATE_DATE));
			ret.setUpdateDate(readTimeStamp(rs,BodyPart.FLD_UPDATE_DATE));
			ret.setCreateUser(rs.getString(BodyPart.FLD_CREATE_USER));
			ret.setUpdateUser(rs.getString(BodyPart.FLD_UPDATE_USER));

			
		} catch (Exception ex) {
			throw new RuntimeException(ex.getMessage());		
		
		}
		ret.setLoading(false);
		ret.setNew(false); // since we load from database, we mark as "old"
		return ret;
    
    }
	 
	
	


	/** Save Parent objects */
@Override
	public void saveParents(ModelObject mo) {

		BodyPart thisMo = (BodyPart)mo;

		if (thisMo.getBodyPart()!=null && thisMo.getBodyPart().isSelfOrRelatedDirty()==true){
			BodyPartDBMapper bodypartMapper= new BodyPartDBMapper(this.getConnection());
			bodypartMapper.save(thisMo.getBodyPart());
			thisMo.setBodyPartId(thisMo.getBodyPart().getBodyPartId());
		}

	}
	
	@Override
	public void fillStatement(ModelObject obj, CallableStatement stmt, boolean bForInsert) throws Exception {
		
		BodyPart o = (BodyPart)obj;
		
		if (o.getBodyPartName()==null){
			stmt.setNull(1, Types.VARCHAR);
		}else{
			stmt.setString(1,o.getBodyPartName());
		}
		if (o.getCreateDate()==null){
			stmt.setNull(2, Types.VARCHAR);
		}else{
			stmt.setTimestamp(2, new java.sql.Timestamp( o.getCreateDate().getTime()));
		}
		if (o.getUpdateDate()==null){
			stmt.setNull(3, Types.VARCHAR);
		}else{
			stmt.setTimestamp(3, new java.sql.Timestamp( o.getUpdateDate().getTime()));
		}
		if (o.getCreateUser()==null){
			stmt.setNull(4, Types.VARCHAR);
		}else{
			stmt.setString(4,o.getCreateUser());
		}
		if (o.getUpdateUser()==null){
			stmt.setNull(5, Types.VARCHAR);
		}else{
			stmt.setString(5,o.getUpdateUser());
		}


		/* PRIMARY KEY FIELD HANDLED BELOW AND SHOULD ALAWAYS BE THE LAST PARAMETER IN THE SQL */
		if (bForInsert){
		 /* No Need to pass anything For INSERTS.  MySQL will assign an autoincrement value, and the MySQLDBMapper will receive it.*/
		} else {
		 /* For Update statement*/
			stmt.setInt(6,o.getBodyPartId().intValue());
		}


	}
	

	
	
	/**
	 * Method used by generated accessor methods of 1-many associations.
	 * It retrieves the object collection using the ApplicationService connection, or 
	 * if that is null, it opens and closes a connection
	 * @param swhere SQL where clause
	 * @param params Parameter array
	 * @return a ModelObjectList of BodyPart objects loaded from database
	 */
	 public static ModelObjectList<BodyPart> getAll(String swhere, Object ... params)  {
		// for static methods w/o connections, we try to get a connection from 
		// the ApplicationService.getCurrentConn().  if we do not find one there, 
		// then we get from the connection pool
		boolean bCloseConn = false;
		Connection c = ApplicationService.getCurrentConn();
		
		try {
			if(c==null) {
				bCloseConn = true;  // since we open a connection from the pool, set the flag to close it.
				c = ConnectionPool.getConn();
				
			}
			BodyPartDBMapper adb = new BodyPartDBMapper(c);
			return adb.findWhere(swhere, params);
		
		}catch (MOTranslatedValidationException moe) {
			throw moe;
		}catch (Exception e) {
			throw new RuntimeException(e);
		} finally {
			if(bCloseConn)DBUtils.closeQuietly(c);
			//// only close the connection if we opened it.
		}
		
	}
	
	/**
	 * Method used by generated accessor methods of 1-1 associations.
	 * It retrieves the object using the ApplicationService connection, or 
	 * if that is null, it opens and closes a connection
	 * @param swhere SQL where clause
	 * @param params Parameter array
	 * @return a single BodyPart object loaded from database
	 */
	public static BodyPart get(String swhere, Object ... params)  {
		
		// for static methods w/o connections, we try to get a connection from 
		// the ApplicationService.getCurrentConn().  if we do not find one there, 
		// then we get from the connection pool
		boolean bCloseConn = false;
		Connection c = ApplicationService.getCurrentConn();
		
		try {
			if(c==null) {
				bCloseConn = true;  // since we open a connection from the pool, set the flag to close it.
				c = ConnectionPool.getConn();
				
			}
			BodyPartDBMapper adb = new BodyPartDBMapper(c);
			return (BodyPart)adb.findOne(swhere, params);
		
		}catch (MOTranslatedValidationException moe) {
			throw moe;
		}catch (Exception e) {
			throw new RuntimeException(e);
		} finally {
			if(bCloseConn)DBUtils.closeQuietly(c);
			//// only close the connection if we opened it.
		}
	}
	
	
	public static BodyPart getByKey(final Object pkey)  {
		
		// for static methods w/o connections, we try to get a connection from 
		// the ApplicationService.getCurrentConn().  if we do not find one there, 
		// then we get from the connection pool
		boolean bCloseConn = false;
		Connection c = ApplicationService.getCurrentConn();
		
		try {
			if(c==null) {
				bCloseConn = true;  // since we open a connection from the pool, set the flag to close it.
				c = ConnectionPool.getConn();
				
			}

			BodyPartDBMapper adb = new BodyPartDBMapper(c);
			return (BodyPart)adb.find(pkey);
		
		}catch (MOTranslatedValidationException moe) {
			throw moe;
		}catch (Exception e) {
			throw new RuntimeException(e);
		} finally {
			if(bCloseConn)DBUtils.closeQuietly(c);
			//// only close the connection if we opened it.
		}
	}
	
	
}