package com.mygym.model;

import com.netu.lib.ApplicationService;
import com.netu.lib.DBUtils;
import com.netu.lib.Model.MODeleteViolationException;
import com.netu.lib.Model.MOTranslatedValidationException;
import com.netu.lib.Model.ModelObject;

import com.netu.lib.db.ConnectionPool;

import com.netu.lib.db.DBMapper;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Types;
import com.netu.lib.Model.ModelObjectList;
import com.netu.lib.db.MySQLDBMapper;
import com.netu.lib.Model.annotations.DMLQueries;

import javax.annotation.Generated;

/**
 * Gen: Version 3, MapperBase.mysql.txt
 * Class autogenerated on <DATE>Wed Jan 20 11:11:46 EET 2021</DATE> by com.netu.codeGen.XMLModelGenerator.<br>
 * Class for Database Data Mapper Pattern for table <b>equipment_exercise</b>.<br>
 * <b>!!!!!!!! DO NOT MODIFY CODE OF THIS CLASS!!!!!!!!</b><br>
 * This class has the responsibility of loading 
 * data into Model Objects, and saving them back to 
 * the Database
 */
@Generated(
        value = {"com.netu.codeGen.XMLModelGenerator"},
        comments = "Mapper Object for table equipment_exercise ",
        date = "Wed Jan 20 11:11:46 EET 2021"
    )
@DMLQueries(
	update="update equipment_exercise set equipment_id=?,exercise_id=? where equipment_exercise_id=?",
	updateRowid="",
	delete="DELETE FROM equipment_exercise WHERE equipment_exercise_id=?",
	deleteRowid="",
	insert="insert into equipment_exercise (equipment_id,exercise_id) values (?,?)",
	selectone="SELECT t.equipment_exercise_id, t.equipment_id, t.exercise_id FROM  equipment_exercise t  WHERE equipment_exercise_id=?",
	selectall="SELECT t.equipment_exercise_id, t.equipment_id, t.exercise_id FROM  equipment_exercise t ",
	pagingSelect="SELECT t.equipment_exercise_id, t.equipment_id, t.exercise_id FROM  equipment_exercise t  {criteria} LIMIT {offset}, {pageSize}")
public class EquipmentExerciseDBMapper extends MySQLDBMapper  {
	
	public EquipmentExerciseDBMapper(Connection c) {
		super(c);
	}
	public EquipmentExerciseDBMapper() {
                // empty constructor, used in dynamic instantiations
		// will get a connection from the ApplicationService
		super();
	}
	
	/**
	* Clients can override this to return a custom class for loading
	*/
	public EquipmentExercise getInstanceForLoad() {
		
		return new EquipmentExercise();
		
	}
		
	public ModelObject load(Object ors) {
		
		ResultSet rs = (ResultSet)ors;
		
		EquipmentExercise ret = this.getInstanceForLoad();
		try {
			ret.setLoading(true);
			
			ret.setEquipmentExerciseId(readInt(rs,EquipmentExercise.FLD_EQUIPMENT_EXERCISE_ID));
			ret.setEquipmentId(readInt(rs,EquipmentExercise.FLD_EQUIPMENT_ID));
			ret.setExerciseId(readInt(rs,EquipmentExercise.FLD_EXERCISE_ID));

			
		} catch (Exception ex) {
			throw new RuntimeException(ex.getMessage());		
		
		}
		ret.setLoading(false);
		ret.setNew(false); // since we load from database, we mark as "old"
		return ret;
    
    }
	 
	
	


	/** Save Parent objects */
@Override
	public void saveParents(ModelObject mo) {

		EquipmentExercise thisMo = (EquipmentExercise)mo;

		if (thisMo.getEquipment()!=null && thisMo.getEquipment().isSelfOrRelatedDirty()==true){
			EquipmentDBMapper equipmentMapper= new EquipmentDBMapper(this.getConnection());
			equipmentMapper.save(thisMo.getEquipment());
			thisMo.setEquipmentId(thisMo.getEquipment().getEquipmentId());
		}

	}
	
	@Override
	public void fillStatement(ModelObject obj, CallableStatement stmt, boolean bForInsert) throws Exception {
		
		EquipmentExercise o = (EquipmentExercise)obj;
		
		if (o.getEquipmentId()==null){
			stmt.setNull(1, Types.VARCHAR);
		}else{
			stmt.setInt(1,o.getEquipmentId());
		}
		if (o.getExerciseId()==null){
			stmt.setNull(2, Types.VARCHAR);
		}else{
			stmt.setInt(2,o.getExerciseId());
		}


		/* PRIMARY KEY FIELD HANDLED BELOW AND SHOULD ALAWAYS BE THE LAST PARAMETER IN THE SQL */
		if (bForInsert){
		 /* No Need to pass anything For INSERTS.  MySQL will assign an autoincrement value, and the MySQLDBMapper will receive it.*/
		} else {
		 /* For Update statement*/
			stmt.setInt(3,o.getEquipmentExerciseId().intValue());
		}


	}
	

	
	
	/**
	 * Method used by generated accessor methods of 1-many associations.
	 * It retrieves the object collection using the ApplicationService connection, or 
	 * if that is null, it opens and closes a connection
	 * @param swhere SQL where clause
	 * @param params Parameter array
	 * @return a ModelObjectList of EquipmentExercise objects loaded from database
	 */
	 public static ModelObjectList<EquipmentExercise> getAll(String swhere, Object ... params)  {
		// for static methods w/o connections, we try to get a connection from 
		// the ApplicationService.getCurrentConn().  if we do not find one there, 
		// then we get from the connection pool
		boolean bCloseConn = false;
		Connection c = ApplicationService.getCurrentConn();
		
		try {
			if(c==null) {
				bCloseConn = true;  // since we open a connection from the pool, set the flag to close it.
				c = ConnectionPool.getConn();
				
			}
			EquipmentExerciseDBMapper adb = new EquipmentExerciseDBMapper(c);
			return adb.findWhere(swhere, params);
		
		}catch (MOTranslatedValidationException moe) {
			throw moe;
		}catch (Exception e) {
			throw new RuntimeException(e);
		} finally {
			if(bCloseConn)DBUtils.closeQuietly(c);
			//// only close the connection if we opened it.
		}
		
	}
	
	/**
	 * Method used by generated accessor methods of 1-1 associations.
	 * It retrieves the object using the ApplicationService connection, or 
	 * if that is null, it opens and closes a connection
	 * @param swhere SQL where clause
	 * @param params Parameter array
	 * @return a single EquipmentExercise object loaded from database
	 */
	public static EquipmentExercise get(String swhere, Object ... params)  {
		
		// for static methods w/o connections, we try to get a connection from 
		// the ApplicationService.getCurrentConn().  if we do not find one there, 
		// then we get from the connection pool
		boolean bCloseConn = false;
		Connection c = ApplicationService.getCurrentConn();
		
		try {
			if(c==null) {
				bCloseConn = true;  // since we open a connection from the pool, set the flag to close it.
				c = ConnectionPool.getConn();
				
			}
			EquipmentExerciseDBMapper adb = new EquipmentExerciseDBMapper(c);
			return (EquipmentExercise)adb.findOne(swhere, params);
		
		}catch (MOTranslatedValidationException moe) {
			throw moe;
		}catch (Exception e) {
			throw new RuntimeException(e);
		} finally {
			if(bCloseConn)DBUtils.closeQuietly(c);
			//// only close the connection if we opened it.
		}
	}
	
	
	public static EquipmentExercise getByKey(final Object pkey)  {
		
		// for static methods w/o connections, we try to get a connection from 
		// the ApplicationService.getCurrentConn().  if we do not find one there, 
		// then we get from the connection pool
		boolean bCloseConn = false;
		Connection c = ApplicationService.getCurrentConn();
		
		try {
			if(c==null) {
				bCloseConn = true;  // since we open a connection from the pool, set the flag to close it.
				c = ConnectionPool.getConn();
				
			}

			EquipmentExerciseDBMapper adb = new EquipmentExerciseDBMapper(c);
			return (EquipmentExercise)adb.find(pkey);
		
		}catch (MOTranslatedValidationException moe) {
			throw moe;
		}catch (Exception e) {
			throw new RuntimeException(e);
		} finally {
			if(bCloseConn)DBUtils.closeQuietly(c);
			//// only close the connection if we opened it.
		}
	}
	
	
}