package com.mygym.model;

/**
 * Class autogenerated on <DATE>Wed Jan 20 11:11:46 EET 2021</DATE> by com.netu.codeGen.XMLModelGenerator
 * Feel Free to change the generated code. 
 */
public class EquipmentExercise extends EquipmentExerciseModelBase  {

  
}
