package com.mygym.model.workout;

import com.netu.lib.ApplicationService;
import com.netu.lib.DBUtils;
import com.netu.lib.Model.MODeleteViolationException;
import com.netu.lib.Model.MOTranslatedValidationException;
import com.netu.lib.Model.ModelObject;

import com.netu.lib.db.ConnectionPool;

import com.netu.lib.db.DBMapper;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Types;
import com.netu.lib.Model.ModelObjectList;
import com.netu.lib.db.MySQLDBMapper;
import com.netu.lib.Model.annotations.DMLQueries;

import javax.annotation.Generated;

/**
 * Gen: Version 3, MapperBase.mysql.txt
 * Class autogenerated on <DATE>Wed Jan 20 12:07:47 EET 2021</DATE> by com.netu.codeGen.XMLModelGenerator.<br>
 * Class for Database Data Mapper Pattern for table <b>workout</b>.<br>
 * <b>!!!!!!!! DO NOT MODIFY CODE OF THIS CLASS!!!!!!!!</b><br>
 * This class has the responsibility of loading 
 * data into Model Objects, and saving them back to 
 * the Database
 */
@Generated(
        value = {"com.netu.codeGen.XMLModelGenerator"},
        comments = "Mapper Object for table workout ",
        date = "Wed Jan 20 12:07:47 EET 2021"
    )
@DMLQueries(
	update="update workout set user_id=?,workout_start=?,workout_end=?,notes=?,scheduled_workout_id=?,workout_definition_id=?,create_date=?,update_date=?,create_user=?,update_user=? where workout_id=?",
	updateRowid="",
	delete="DELETE FROM workout WHERE workout_id=?",
	deleteRowid="",
	insert="insert into workout (user_id,workout_start,workout_end,notes,scheduled_workout_id,workout_definition_id,create_date,update_date,create_user,update_user) values (?,?,?,?,?,?,?,?,?,?)",
	selectone="SELECT t.workout_id, t.user_id, t.workout_start, t.workout_end, t.notes, t.scheduled_workout_id, t.workout_definition_id, t.create_date, t.update_date, t.create_user, t.update_user FROM  workout t  WHERE workout_id=?",
	selectall="SELECT t.workout_id, t.user_id, t.workout_start, t.workout_end, t.notes, t.scheduled_workout_id, t.workout_definition_id, t.create_date, t.update_date, t.create_user, t.update_user FROM  workout t ",
	pagingSelect="SELECT t.workout_id, t.user_id, t.workout_start, t.workout_end, t.notes, t.scheduled_workout_id, t.workout_definition_id, t.create_date, t.update_date, t.create_user, t.update_user FROM  workout t  {criteria} LIMIT {offset}, {pageSize}")
public class ExecutedWorkoutDBMapper extends MySQLDBMapper  {
	
	public ExecutedWorkoutDBMapper(Connection c) {
		super(c);
	}
	public ExecutedWorkoutDBMapper() {
                // empty constructor, used in dynamic instantiations
		// will get a connection from the ApplicationService
		super();
	}
	
	/**
	* Clients can override this to return a custom class for loading
	*/
	public ExecutedWorkout getInstanceForLoad() {
		
		return new ExecutedWorkout();
		
	}
		
	public ModelObject load(Object ors) {
		
		ResultSet rs = (ResultSet)ors;
		
		ExecutedWorkout ret = this.getInstanceForLoad();
		try {
			ret.setLoading(true);
			
			ret.setWorkoutId(readInt(rs,ExecutedWorkout.FLD_WORKOUT_ID));
			ret.setUserId(readInt(rs,ExecutedWorkout.FLD_USER_ID));
			ret.setWorkoutStart(readTimeStamp(rs,ExecutedWorkout.FLD_WORKOUT_START));
			ret.setWorkoutEnd(readTimeStamp(rs,ExecutedWorkout.FLD_WORKOUT_END));
			ret.setNotes(rs.getString(ExecutedWorkout.FLD_NOTES));
			ret.setScheduledWorkoutId(readInt(rs,ExecutedWorkout.FLD_SCHEDULED_WORKOUT_ID));
			ret.setWorkoutDefinitionId(readInt(rs,ExecutedWorkout.FLD_WORKOUT_DEFINITION_ID));
			ret.setCreateDate(readTimeStamp(rs,ExecutedWorkout.FLD_CREATE_DATE));
			ret.setUpdateDate(readTimeStamp(rs,ExecutedWorkout.FLD_UPDATE_DATE));
			ret.setCreateUser(rs.getString(ExecutedWorkout.FLD_CREATE_USER));
			ret.setUpdateUser(rs.getString(ExecutedWorkout.FLD_UPDATE_USER));

			
		} catch (Exception ex) {
			throw new RuntimeException(ex.getMessage());		
		
		}
		ret.setLoading(false);
		ret.setNew(false); // since we load from database, we mark as "old"
		return ret;
    
    }
	 
	
	



	
	@Override
	public void fillStatement(ModelObject obj, CallableStatement stmt, boolean bForInsert) throws Exception {
		
		ExecutedWorkout o = (ExecutedWorkout)obj;
		
		if (o.getUserId()==null){
			stmt.setNull(1, Types.VARCHAR);
		}else{
			stmt.setInt(1,o.getUserId());
		}
		if (o.getWorkoutStart()==null){
			stmt.setNull(2, Types.VARCHAR);
		}else{
			stmt.setTimestamp(2, new java.sql.Timestamp( o.getWorkoutStart().getTime()));
		}
		if (o.getWorkoutEnd()==null){
			stmt.setNull(3, Types.VARCHAR);
		}else{
			stmt.setTimestamp(3, new java.sql.Timestamp( o.getWorkoutEnd().getTime()));
		}
		if (o.getNotes()==null){
			stmt.setNull(4, Types.VARCHAR);
		}else{
			stmt.setString(4,o.getNotes());
		}
		if (o.getScheduledWorkoutId()==null){
			stmt.setNull(5, Types.VARCHAR);
		}else{
			stmt.setInt(5,o.getScheduledWorkoutId());
		}
		if (o.getWorkoutDefinitionId()==null){
			stmt.setNull(6, Types.VARCHAR);
		}else{
			stmt.setInt(6,o.getWorkoutDefinitionId());
		}
		if (o.getCreateDate()==null){
			stmt.setNull(7, Types.VARCHAR);
		}else{
			stmt.setTimestamp(7, new java.sql.Timestamp( o.getCreateDate().getTime()));
		}
		if (o.getUpdateDate()==null){
			stmt.setNull(8, Types.VARCHAR);
		}else{
			stmt.setTimestamp(8, new java.sql.Timestamp( o.getUpdateDate().getTime()));
		}
		if (o.getCreateUser()==null){
			stmt.setNull(9, Types.VARCHAR);
		}else{
			stmt.setString(9,o.getCreateUser());
		}
		if (o.getUpdateUser()==null){
			stmt.setNull(10, Types.VARCHAR);
		}else{
			stmt.setString(10,o.getUpdateUser());
		}


		/* PRIMARY KEY FIELD HANDLED BELOW AND SHOULD ALAWAYS BE THE LAST PARAMETER IN THE SQL */
		if (bForInsert){
		 /* No Need to pass anything For INSERTS.  MySQL will assign an autoincrement value, and the MySQLDBMapper will receive it.*/
		} else {
		 /* For Update statement*/
			stmt.setInt(11,o.getWorkoutId().intValue());
		}


	}
	

	
	
	/**
	 * Method used by generated accessor methods of 1-many associations.
	 * It retrieves the object collection using the ApplicationService connection, or 
	 * if that is null, it opens and closes a connection
	 * @param swhere SQL where clause
	 * @param params Parameter array
	 * @return a ModelObjectList of ExecutedWorkout objects loaded from database
	 */
	 public static ModelObjectList<ExecutedWorkout> getAll(String swhere, Object ... params)  {
		// for static methods w/o connections, we try to get a connection from 
		// the ApplicationService.getCurrentConn().  if we do not find one there, 
		// then we get from the connection pool
		boolean bCloseConn = false;
		Connection c = ApplicationService.getCurrentConn();
		
		try {
			if(c==null) {
				bCloseConn = true;  // since we open a connection from the pool, set the flag to close it.
				c = ConnectionPool.getConn();
				
			}
			ExecutedWorkoutDBMapper adb = new ExecutedWorkoutDBMapper(c);
			return adb.findWhere(swhere, params);
		
		}catch (MOTranslatedValidationException moe) {
			throw moe;
		}catch (Exception e) {
			throw new RuntimeException(e);
		} finally {
			if(bCloseConn)DBUtils.closeQuietly(c);
			//// only close the connection if we opened it.
		}
		
	}
	
	/**
	 * Method used by generated accessor methods of 1-1 associations.
	 * It retrieves the object using the ApplicationService connection, or 
	 * if that is null, it opens and closes a connection
	 * @param swhere SQL where clause
	 * @param params Parameter array
	 * @return a single ExecutedWorkout object loaded from database
	 */
	public static ExecutedWorkout get(String swhere, Object ... params)  {
		
		// for static methods w/o connections, we try to get a connection from 
		// the ApplicationService.getCurrentConn().  if we do not find one there, 
		// then we get from the connection pool
		boolean bCloseConn = false;
		Connection c = ApplicationService.getCurrentConn();
		
		try {
			if(c==null) {
				bCloseConn = true;  // since we open a connection from the pool, set the flag to close it.
				c = ConnectionPool.getConn();
				
			}
			ExecutedWorkoutDBMapper adb = new ExecutedWorkoutDBMapper(c);
			return (ExecutedWorkout)adb.findOne(swhere, params);
		
		}catch (MOTranslatedValidationException moe) {
			throw moe;
		}catch (Exception e) {
			throw new RuntimeException(e);
		} finally {
			if(bCloseConn)DBUtils.closeQuietly(c);
			//// only close the connection if we opened it.
		}
	}
	
	
	public static ExecutedWorkout getByKey(final Object pkey)  {
		
		// for static methods w/o connections, we try to get a connection from 
		// the ApplicationService.getCurrentConn().  if we do not find one there, 
		// then we get from the connection pool
		boolean bCloseConn = false;
		Connection c = ApplicationService.getCurrentConn();
		
		try {
			if(c==null) {
				bCloseConn = true;  // since we open a connection from the pool, set the flag to close it.
				c = ConnectionPool.getConn();
				
			}

			ExecutedWorkoutDBMapper adb = new ExecutedWorkoutDBMapper(c);
			return (ExecutedWorkout)adb.find(pkey);
		
		}catch (MOTranslatedValidationException moe) {
			throw moe;
		}catch (Exception e) {
			throw new RuntimeException(e);
		} finally {
			if(bCloseConn)DBUtils.closeQuietly(c);
			//// only close the connection if we opened it.
		}
	}
	
	
}