package com.mygym.model.workout;

/**
 * Class autogenerated on <DATE>Wed Jan 20 12:07:47 EET 2021</DATE> by com.netu.codeGen.XMLModelGenerator
 * Feel Free to change the generated code. 
 */
public class WorkoutExercise extends WorkoutExerciseModelBase  {

  
}
